version: "3.7"
services:
  app:
    build:
      args:
        user: willy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: uas-pweb
    container_name: uas-pweb
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - uas-pweb

  nginx:
    image: nginx:alpine
    container_name: uas-pweb-nginx
    restart: unless-stopped
    ports:
      - 8093:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - uas-pweb

networks:
  uas-pweb:
    driver: bridge